

#------------------------------------------------------------------------------
# CORE
#------------------------------------------------------------------------------

    UI_URL: 'localhost-core'
    CORE_URL: 'localhost-core'

    # Advanced configuration.
    CORE_DEVELOPMENT: 'false'
    POSTGRESQL_VOLUME: 'db_postgres11'
    MONGODB_VOLUME: 'db_mongo'

    WEB_UI_DEVELOPMENT: 'false'
#------------------------------------------------------------------------------
# IMS
#------------------------------------------------------------------------------
  
    IMS_URL: 'localhost-ims'
    UPLOAD_URL: 'localhost-upload'

    IMS_STORAGE_PATH: '/data/images'
    IMS_BUFFER_PATH: '/tmp/uploaded'
    FAST_DATA_PATH: '/data/images'
    PROXY_CACHE_PATH: '/data/cache'

    # Advanced configuration.
    IMS_DEVELOPMENT: 'false'

    IIP_OFF_URL: 'localhost-iip-cyto'
    IIP_CYTO_URL: 'localhost-iip-cyto'
    MEMCACHED_PASS: "mypass"
    NB_IIP_PROCESS: '10'

#------------------------------------------------------------------------------
# PLUGIN: BACKUP
#------------------------------------------------------------------------------
   
    SENDER_EMAIL_SMTP_HOST: 'smtp.gmail.com'
    SENDER_EMAIL_SMTP_PORT: '587'
    SENDER_EMAIL_PASS: 'passwd'
    SENDER_EMAIL: 'your.email@gmail.com'

    BACKUP_ENABLED: 'false'
    RECEIVER_EMAIL: 'receiver@XXX.com'
    BACKUP_PATH: '/data/backup'

#------------------------------------------------------------------------------
# PLUGIN: RETRIEVAL
#------------------------------------------------------------------------------
# retrieval:    
#     RETRIEVAL_ENABLED: 'false'
#     RETRIEVAL_URL: 'localhost-retrieval'
#     RETRIEVAL_PATH: '/data/thumb'

#     # Advanced configuration.
#     RETRIEVAL_PASSWORD: 'retrieval_default'
#     RETRIEVAL_ENGINE: 'redis' #possible values : memory, redis

#------------------------------------------------------------------------------
# PLUGIN: BIOFORMAT
#------------------------------------------------------------------------------
  
    BIOFORMAT_ENABLED: 'true'
    BIOFORMAT_DEVELOPMENT: 'false'

#------------------------------------------------------------------------------
# PLUGIN: IIP-JP2 (JPEG 2000 native support)
#------------------------------------------------------------------------------
  
    IIP_JP2_ENABLED: 'true'

    # Advanced configuration.
    IIP_JP2_URL: 'localhost-iip-jp2000'

#------------------------------------------------------------------------------
# PLUGIN: IRIS
#------------------------------------------------------------------------------
# iris:    
#     IRIS_ENABLED: 'false'
#     IRIS_URL: 'localhost-iris'
#     IRIS_ADMIN_NAME: "Ian Admin"
#     IRIS_ADMIN_ORGANIZATION_NAME: "University of Somewhere, Department of Whatever"
#     IRIS_ADMIN_EMAIL: "ian.admin@somewhere.edu"

#     # Advanced configuration.
#     IRIS_ID: "LOCAL_CYTOMINE_IRIS"
#     IRIS_VOLUME: 'iris_data'

#------------------------------------------------------------------------------
# PLUGIN: SOFTWARE
#------------------------------------------------------------------------------
  
    SOFTWARE_ENABLED: 'true'
    SOFTWARE_CODE_PATH: '/data/softwares/code'
    SOFTWARE_DOCKER_IMAGES_PATH: '/data/softwares/images'
    JOBS_PATH: '/data/jobs'
    SERVER_SSHKEYS_PATH: '/data/ssh'

    # Advanced configuration.
    RABBITMQ_LOGIN: "router"
    RABBITMQ_PASSWORD: "router"
    SLURM_VOLUME: 'slurm_data'

# #-------------------------------------------------------------------------------
# # HTTPS FOR PUBLIC URLS
# #-------------------------------------------------------------------------------

# # Protocol for URLs accessible from outside (CORE_URL, IMS_URL, UPLOAD_URL, IRIS_URL)
    HTTP_PROTOCOL: 'http' # Accepted values: http, https
# HTTP_PROXY=false

# # Path where certificates are stored:
    CERTIFICATE_PATH: '/data/certificates'  #que NGINX!!!!!!

# # To use HTTPS protocol, you need the following certificates in your CERTIFICATE_PATH
# # - ${CORE_URL}.pem (ex: localhost-core.pem)
# # - ${CORE_URL}-key.pem (ex: localhost-core-key.pem)
# # - ${IMS_URL}.pem
# # - ${IMS_URL}-key.pem
# # - ${UPLOAD_URL}.pem
# # - ${UPLOAD_URL}-key.pem
# # - ${IRIS_URL}.pem - only if $IRIS_ENABLED = true
# # - ${IRIS_URL}-key.pem - only if $IRIS_ENABLED = true

# HTTP_NGINX_PORT=80
# HTTPS_NGINX_PORT=443