apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-postgres11
  name: db-postgres11
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 100Mi
status: {}
